### ISSUE TITLE
Incorrect usage of Documents directory.

### ISSUE THREAD

**Issue by constantine-fry** [ibm-mobile-push/ios#10]
The library stores `mce-details.txt` and `com.***** 2018-02-05 13-17.log` in **Documents** directory. According to [File System Basics](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) this directory should be used only to store user generated content such as PDF documents, Images, etc. 
> **Documents Derictory**:  Use this directory to store user-generated content. The contents of this directory can be made available to the user through file sharing; therefore, his directory should only contain files that you may wish to expose to the user. The contents of this directory are backed up by iTunes and iCloud.

<img width="441" alt="screen shot 2018-02-05 at 14 27 23" src="https://user-images.githubusercontent.com/239692/35806718-c7904fe8-0a80-11e8-89af-e32aa86d379a.png">

**Comment by andrewcib** [comment]
Thanks, fixed.
