### ISSUE TITLE
Files in Library directory

### ISSUE THREAD

**Issue by constantine-fry** [ibm-mobile-push/ios#11]
To avoid name collisions with other files in Library directory it's recommended for libraries to store files in their own directory eg: `Library/com.ibm.mobile-push`. 
<img width="441" alt="screen shot 2018-02-05 at 14 27 23" src="https://user-images.githubusercontent.com/239692/35807142-2dd942b8-0a82-11e8-880e-bce24ff80cd5.png">

**Comment by jbuchman** [comment]
We will address this in 3.7.1.2 by moving the files to a subdirectory, thanks for the input
