### ISSUE TITLE
Names for notification are not unique.

### ISSUE THREAD

**Issue by constantine-fry** [ibm-mobile-push/ios#12]
```objc
/** The RegisteredNotification message is sent via NSNotificationCenter when the SDK registers with the IBM servers */
static NSString * const RegisteredNotification = @"RegisteredNotification";

/** The RegistrationChangedNotification message is sent via NSNotificationCenter when the userId or channelId change durring the phone home process */
static NSString * const RegistrationChangedNotification = @"RegistrationChangedNotification";
```

Many values in MCEConstants.h are not unique. For instance `RegisteredNotification` might be already used by an application and that might lead to bugs which are hard to debug. It's recommended for libraries to define constants with unique names and unique values. Prefixing this keys with MCE would already be a good solution, but you anyway can come up with longe name :)

static NSString * const MCERegisteredNotification = @"MCERegisteredNotification";

**Comment by jbuchman** [comment]
We will address this by prefixing the registration notifications with "MCE" in the 3.7.1.2 release, thanks for the input
