### ISSUE TITLE
Insert Data to database from iOS

### ISSUE THREAD

**Issue by NayanBhut** [ibm-mobile-push/ios#18]
Is there any way that I can insert, update or delete data to the server?
Like in IBM console I had created a shared database "Test Database" and columns are "device token", "name", "username", "emailId". I have to insert the data directly there using the iPhone and how am I directly send notifications, actions from API.

**Comment by andrewcib** [comment]
Use the updateUserAttribute API - on iOS, that's in [MCEAttributesQueueManager](https://developer.ibm.com/static/site-id/106/MobilePush300/ObjectiveCAPI_Reference/Classes/MCEAttributesQueueManager.html).

**Comment by andrewcib** [comment]
API to set/update (updateUserAttributes) and delete (deleteUserAttributes) is already available.

**Comment by NayanBhut** [comment]
How do I know where data in inserted? If I have a database name "TestDB" where do I define database name in that.
