### ISSUE TITLE
autoInitializeFlag is ignored

### ISSUE THREAD

**Issue by sbandol** [ibm-mobile-push/ios#3]
Hello,

I'm integrating the SDK following this documentation:
http://www.ibm.com/support/knowledgecenter/SSMRK7_3.0.0/AppPush/Apple_iOS/implement_ios_sdk.html

and trying to manually initialize MCESdk by setting this in MceConfig.json:
   ` "autoInitializeFlag": false`

then at some point (when user is logged in) i call:
`MCESdk.sharedInstance().manualInitialization()`

But i see this log generated by the SDK (`"loglevel": "verbose"`):
`Auto Initialize is ON`
even before the i call `manualInitialization`

Does that means MCESdk is ignoring `autoInitializeFlag`flag in the .json? 

Thanks,
StaS

--
Update: 
Same behaviour in the sample project provided in this repo just by changing:
```
    "autoInitializeFlag": false,
    "loglevel": "verbose",
```

I get:

`2016-12-20 13:39:18:186 SwiftSample[28358:403] Auto Initialize is ON`

**Comment by jbuchman** [comment]
It turns out that the config file is wrong, the correct flag name is "autoInitialize" not "autoInitializeFlag". We'll fix the default config that in the next release, but for now you can just replace the key name in your config.
