### ISSUE TITLE
Add multiple appKeys

### ISSUE THREAD

**Issue by RodolfoAntonici** [ibm-mobile-push/ios#5]
I'm running into a trouble: we have more than 2 ambients on our project because of the application bundle ID, so there's a way to add more keys one the MCEConfig.json and choose what key to use when the MCESDK starts?

**Comment by vojtaBelovsky** [comment]
I have same issue, I have one sources, 4 configurations and 4 targets. So I have to build 16 apps with different App IDs ( different for different development, testing and production purposes ). I tried not to include appKey into config JSON, in that case your SDK is showing error:

devAppKey is invalid should start with 'ap', 10 character long and should not be null.

So there is no way for me to include your SDK to my application. I need to determine AppKey at runtime, not at buildtime.

**Comment by RodolfoAntonici** [comment]
Well, seems that IBM don't want to prioritize this so I did a little workaround. I've configured multiple targets on my project and placed the MCEConfig.json on 3 separated folders: Default, AdhocDev, AdhocProd, each file has different targets and that solves the case.
Why in different folders: IBM Api look for the file on the main bundle, since you can't have the same file name on the same folder.

**Comment by vojtaBelovsky** [comment]
Yeah, I was thinking about that, but imagine how many targets I would have to create.. that would cause much worse maintenance during development. And this rework of project structure would also break our automatic build generator, so another work. I'm thinking about writing script that will be called before build starts and this scrip will add correct appKeys to the config file.

**Comment by andrewcib** [comment]
Two options are a build script which copies different MceConfig.json files into the right place as appropriate, or setting the configuration in code entirely using https://developer.ibm.com/static/site-id/106/MobilePush300/ObjectiveCAPI_Reference/Classes/MCEConfig.html#//api/name/sharedInstanceWithDictionary:
