### ISSUE TITLE
Missing agreement

### ISSUE THREAD

**Issue by constantine-fry** [ibm-mobile-push/ios#7]
>BY DOWNLOADING, INSTALLING, COPYING, ACCESSING, CLICKING ON AN “ACCEPT” BUTTON, OR OTHERWISE USING THE PROGRAM, LICENSEE AGREES TO THE TERMS OF THIS AGREEMENT. https://developer.ibm.com/customer-engagement/mobile-app-messaging/

Hi guys,
I just want to let you know that I wasn't able to find the aggreement at given URL.

**Comment by andrewcib** [comment]
Thanks, updated
